package sshutil

import (
	"bufio"
	"errors"
	"os"
	"regexp"
	"strconv"
	"strings"

	"golang.org/x/crypto/ssh"
)

const (
	DEFAULT_SSH_PORT    = 22
	KNOWN_HOSTS_COMMENT = "Added by oinit"
	CONFIG_COMMENT      = `# This 'Match' block was added by oinit.
#
# Please make sure it stays positioned on top of your ssh config
# file, assuring it will be applied before other 'Host' or 'Match'
# blocks that may interfere with oinit.`
)

// GenerateKnownHosts returns a string that can be added to the user or system
// known_hosts file. The returned string does not end with a line break.
func GenerateKnownHosts(host, port, pubkey string) (string, error) {
	var combinedHost string

	if port == strconv.Itoa(DEFAULT_SSH_PORT) {
		combinedHost = host
	} else {
		// Enclose host within brackets for non-standard port as required by OpenSSH.
		// From sshd(8):
		//   A hostname or address may optionally be enclosed within ‘[’ and ‘]’ brackets then followed by ‘:’ and a
		//   non-standard port number.
		combinedHost = "[" + host + "]:" + port
	}

	// Reject host names containing whitespace, which would otherwise break the
	// single-line known_hosts entry.
	if strings.ContainsAny(combinedHost, " \t\r\n") {
		return "", errors.New("invalid host")
	}

	// Parse and re-serialize the key returned by the CA rather than trusting
	// the raw string. Besides rejecting malformed input, this prevents a
	// malicious or spoofed CA from injecting additional known_hosts lines
	// (for example a global "@cert-authority *" that would trust the attacker
	// for every host) via newlines embedded in the "public key".
	parsed, _, _, _, err := ssh.ParseAuthorizedKey([]byte(pubkey))
	if err != nil {
		return "", errors.New("invalid pubkey format")
	}

	key := strings.TrimSuffix(string(ssh.MarshalAuthorizedKey(parsed)), "\n")

	return "@cert-authority " + combinedHost + " " + key, nil
}

// AddSSHKnownHost adds a "@cert-authority <hostport> <public key>" to the users
// known_hosts file if not already present there or system wide.
func AddSSHKnownHost(host, port, pubkey string) error {
	paths, err := PathsSSHKnownHosts()
	if err != nil {
		return err
	}

	add, err := GenerateKnownHosts(host, port, pubkey)
	if err != nil {
		return err
	}

	for _, path := range []string{paths.System, paths.User} {
		f, err := os.Open(path)
		if err != nil {
			continue
		}
		defer f.Close()

		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			if strings.HasPrefix(scanner.Text(), add) {
				return nil
			}
		}
	}

	f, err := os.OpenFile(paths.User, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}

	if _, err = f.Write([]byte(add + " " + KNOWN_HOSTS_COMMENT + "\n")); err != nil {
		f.Close()
		return err
	}

	f.Close()

	return nil
}

func GenerateMatchBlock() string {
	return "Match exec \"oinit match %h %p\"\n\tUser oinit\n\tIdentityFile ~/.ssh/oinit_%h_%p\n\tCertificateFile ~/.ssh/oinit_%h_%p-cert.pub"
}

// matchBlockRe recognises an already-present oinit "Match exec" line. It matches
// generously so an operator's customised invocation is still detected: leading
// whitespace, case-insensitive keywords, and any command that runs "oinit match"
// (e.g. an absolute path like "/usr/bin/oinit match %h %p") all count.
var matchBlockRe = regexp.MustCompile(`(?i)^\s*Match\s+exec\s+.*oinit\s+match`)

// hasMatchBlock reports whether line is an oinit "Match exec" directive.
func hasMatchBlock(line string) bool {
	return matchBlockRe.MatchString(line)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)

	return !errors.Is(err, os.ErrNotExist)
}

// AddSSHMatchBlock adds the string generated by GenerateMatchBlock() to the
// user's ssh config file, if not already present there or system-wide.
// Returns boolean that indicates whether the match block was added or not.
func AddSSHMatchBlock() (bool, error) {
	paths, err := PathsSSHConfig()
	if err != nil {
		return false, err
	}

	// Search for an existing oinit 'Match exec ... oinit match ...' line. The
	// check is deliberately generous (see matchBlockRe) so a block whose command
	// the operator has customised - e.g. an absolute "/usr/bin/oinit" path - is
	// still recognised and not duplicated.
	block := GenerateMatchBlock()

	for _, path := range []string{paths.System, paths.User} {
		f, err := os.Open(path)
		if err != nil {
			continue
		}
		defer f.Close()

		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			if hasMatchBlock(scanner.Text()) {
				return false, nil
			}
		}
	}

	// Prepend match block to user's ssh config file by reading the existing
	// content, prepending the string and writing to file using truncate.

	var content []byte

	if fileExists(paths.User) {
		content, err = os.ReadFile(paths.User)

		if err != nil {
			// File exists but could not read contents. To prevent overwriting
			// the file, return error
			return false, err
		}
	}

	newContent := []byte(CONFIG_COMMENT + "\n" + block + "\n\n")
	newContent = append(newContent, content...)

	if err := os.WriteFile(paths.User, newContent, 0644); err != nil {
		return false, err
	}

	return true, err
}
